---
- name: update_cache
  tags: always
  hosts: all
  become: true
  tasks: 
    - name: Update package cache
      ansible.builtin.package:
        update_cache: yes
        name:
          - plocate
          - git
          - npm

- name: install apache2
  tags: apache
  hosts: apache-servers
  become: true
  tasks:
    - name: Install Apache2
      ansible.builtin.package:
        name: apache2
        state: latest

- name: install-kubernetes
  tags: kubernetes
  hosts: kubernetes-server
  become: true
  tasks:
    - name: Install Kubernetes
      ansible.builtin.package:
        name: kubernetes
        state: latest

- name: copy-git-repo
  tags: git
  hosts: copy-git-repo
  become: true
  tasks:
    - name: Copy Git repo
      ansible.builtin.git:
        dest: /home/ubuntu-server1/AWS
        repo: https://github.com/verma-kunal/AWS-Session.git
        clone: yes
        force: yes

- name: install-DB
  tags: db
  hosts: db-servers
  become: true
  tasks:
    - name: Install MariaDB server & ansible
      ansible.builtin.package:
        name: 
          - mariadb-server
          - ansible
        state: latest

- name: copy from server to nodes
  tags: copy
  hosts: copy-servers
  become: true
  tasks:
    - ansible.builtin.copy:
        src: /home/amrkedra/Downloads/GitHub_API_Collection_2023.json
        dest: /home/copied-folder/
        mode: 644
        group: root
        remote_src: no

- name: install unzip + terraform
  tags: terraform
  hosts: terraform
  become: on
  tasks:
    - name: install unzip
      ansible.builtin.package:
          name: unzip
          state: latest

    - name: download terraform
      ansible.builtin.get_url:
          url: https://releases.hashicorp.com/terraform/0.15.5/terraform_0.15.5_linux_amd64.zip
          dest: /tmp/terraform.zip

    - name: extract terraform archive
      ansible.builtin.unarchive:
        src: /tmp/terraform.zip
        dest: /usr/local/bin/
        remote_src: on
        creates: /usr/local/bin/terraform

    - name: set exuctable permission
      ansible.builtin.file:
        path: /usr/local/bin/terraform
        mode: 741
