---
- name: update_cache
  hosts: all
  become: true
  tasks: 
  - ansible.builtin.package:
      update_cache: true
      name:
      - plocate
      - git
      - npm

- name: install apache2 
  hosts: apache-servers
  become: true
  tasks:
   - ansible.builtin.package:
      name: apache2
      state: latest

- name: install-kubernetes
  hosts: kubernetes-server
  become: true
  tasks:
    - ansible.builtin.package:
        name: kubernetes
        state: latest

- name: copy-git-repo
  hosts: copy-git-repo
  become: true
  tasks:
    - ansible.builtin.git:
        dest: /home/ubuntu-server1/AWS
        repo: https://github.com/verma-kunal/AWS-Session.git
        clone: true
        force: true

- name: install-DB
  hosts: db-servers
  become: true
  tasks:
    - ansible.builtin.package:
        name: mariadb-server
        state: latest