#!/bin/bash
#this is my own aliases for using git commands
#will keep adding commands and aliases as i progress


alias ginit='git init' #to initiate a new repo
alias gadd='git add.' #to add all fils to stage
alias gcom='git commit -m " " ' #to commit the added files
alias gpush='git push --force' #to force push the files to the repo
alias giff='git diff' # to show the difference between versions
alias gstat='git status' #to show the current repo status
alias glog='git log' #to show all logs of the repo
alias gstash='git stash -u' #to stash the files including the untracked files
alias gmote='git remote -v' #to show the current remote repo for push and pull
git remote add origin 'the repo url' #to link the local repo to the desired online repo
git branch -m main #to choose to work on main branch
git remote -v #shows which remote repo this one fetching from and pushing to
git switch <branch name> #to shwitch to specific branch
git branch -D #deletes the branch
git stash -u #adds all files which staged to stash
git stash --<file name> #moves this particular file to stash
git checkout -b #creates new branch and moves to it directly
git stash pop #to move the stashed files and bring them to stage
git stash clear #to empty stash
git stash list #lists the stash content
git stash drop <file ID> #to delete file from stash 
git stash apply #to pop file from stash but keep copy of it in stash 

