#!/bin/bash
#this is my own aliases for using git commands
#will keep adding commands and aliases as i progress


alias ginit='git init' #to initiate a new repo
alias gadd='git add.' #to add all fils to stage
alias gcom='git commit -m " " ' #to commit the added files
alias gpush='git push --force' #to force push the files to the repo
alias giff='git diff' # to show the difference between versions
alias gstat='git status' #to show the current repo status
alias glog='git log' #to show all logs of the repo
alias gstash='git stash -u' #to stash the files including the untracked files
alias gmote='git remote -v' #to show the current remote repo for push and pull
git remote add origin 'the repo url' #to link the local repo to the desired online repo
git branch -m main #to choose to work on main branch
git revert <commit hash code> #to revert to specific commit point
git checkout -b #to create a branch and auto change to work on it
git branch -d or D #to delete branch 'd' is to safley delete it 'D' to force delete
git branch -m # to rename the branch
