# yaml-language-server: $schema='none'
- name: install apache2
  tags: apache
  hosts: apache-servers
  become: true
  tasks:
  - name: Install Apache2
    ansible.builtin.package:
      name: apache2
      state: latest
    tags: apache

  - name: start apache2 service
    ansible.builtin.service:
      name: apache2
      state: stopped
      enabled: true
    tags: apache
    register: apache_service_started

  - name: restart apache service
    ansible.builtin.service:
      name: apache2
      state: restarted
    when: apache_service_started.changed    
  