apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: default
  labels:
    app: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: amrkedra/flask-app:v8
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 130m
            memory: 300Mi
        ports:
        - containerPort: 5000
        env:
        - name: REDIS_HOST
          value: "redis.redis.svc.cluster.local" # Updated FQDN
        - name: REDIS_PORT
          value: "85"
        - name: DB_NAME
          value: "flask-db"
