apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql-server
  namespace: default
  labels:
    app: sql-server
spec:
  selector:
    matchLabels:
      app: sql-server
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sql-server
    spec:
      containers:
      - name: sql-server
        image: mysql:8.0  # Updated to a more common MySQL image
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: db-vol-mounted
          mountPath: "/var/lib/mysql"  # Common MySQL data directory
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "12345a"
        - name: MYSQL_DATABASE
          value: "mydatabase"  # Example database name
        - name: MYSQL_USER
          value: "db_user"
        - name: MYSQL_PASSWORD
          value: "db_pass"
        ports:
        - containerPort: 3306
          name: mysql
        - containerPort: 33060
          name: mysqlx
      volumes:
      - name: db-vol-mounted
        persistentVolumeClaim:
          claimName: myclaim
    
---

kind: Service
apiVersion: v1
metadata:
  name: my-sql-service
spec:
  selector:
    app: sql-server
  type: ClusterIP
  ports:
  - name: db-port-mysql
    port: 3306
    targetPort: 3306
  - name: db-port-mysqlx
    port: 33060
    targetPort: 33060
