apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota
  namespace: default
spec:
  hard:
    cpu: "2" # Limit of 2 CPU cores
    memory: 2Gi # Limit of 2 GiB memory
    pods: 1 # Maximum of 2 pods
