all:
  children:
    masters:
      hosts:
        master:
          ansible_host: 192.168.1.4
          ansible_user: amrkedra
          ansible_ssh_private_key_file: ./vm-rsa-key
    workers:
      hosts:
        worker:
          ansible_host: 192.168.1.9
          ansible_user: amrkedra
          ansible_ssh_private_key_file: ./vm-rsa-key

    k8s_cluster:
      children:
        masters: {}
        workers: {}
