apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-pod
  namespace: default
  labels:
    app: ubuntu-pod
spec:
  containers:
  - name: ubuntu-pod
    image: ubuntu:22.04
    command: ["sleep", "infinity"]
    resources:
      limits:
        cpu: 500m
        memory: 1000Mi
      requests:
        cpu: 500m
        memory: 1000Mi
